#!/usr/bin/env bash
# This script kills the 7-highlander process using SIGKILL (signal 9)

# Find the PID of 7-highlander
PID=$(pgrep -f 7-highlander)

# Kill the process using SIGKILL
if [ -n "$PID" ]; then
    kill -9 "$PID"
fi
